######################################
#   _   _ ___ ___  _   _  ___ _  __  #
#  | | | | _ \   \| | | |/ __| |/ /  #
#  | |_| |  _/ |) | |_| | (__| ' <   #
#   \___/|_| |___/ \___/ \___|_|\_\  #
#                                    #
######################################
# ╔════════════════════════════════╗ #
# ║   Quacking Down on Downtime!   ║ #
# ╚════════════════════════════════╝ #
######################################
blank_issues_enabled: false