name: ðŸ—³ï¸ Feature request
description: gimme gimme gimme
body:
  - type: textarea
    id: request
    attributes:
      label: ðŸ“ƒ Feature request
      description: Tell us what you'd like to see added in future versions
      placeholder: >-
        I'd like to see all ducks replaced with geese
    validations:
      required: true
